### ISSUE TITLE
usage examples and questions

### ISSUE THREAD

**Issue by jianshu93** [jedisct1/rust-polymur-hash#1]
Dear @jedisct1,

Many thanks for implement/import the polymurhash from C. I noticed that there is no example usage in the home page but the benchmark is successful. I want to obtain some random number like this using Wyhash (https://github.com/wangyi-fudan/wyhash, https://github.com/eldruin/wyhash-rs):

let mut rng2 = WyRng::seed_from_u64(k as u64 + 123743);

to approximate the effect of universal hash function, but wyhash is not proved to be universal hash library. How can I get it using polymurhash, which is proven to be almost universal.

Thanks,

Jianshu

**Comment by jedisct1** [comment]
One way to use polymurhash as a RNG would be to call `hash_with_tweak()` with an empty message and the tweak being incremented after each output.

Ideally the compiler would notice that the message is constant and optimize out the length checks and additions in `poly1611()`, but Rust usually performs very poorly in such cases, so I'm not sure.

**Comment by jianshu93** [comment]
hello @jedisct1,
in that case, I think I will just use the hash function instead of RNGs. I was trying to densify some vectors by mapping some non-empty bins to empty bins via universal hash function. I did it using RNG by using the position of non-empty bins as seed (k in the above case). The algorithm is attached, in this case I just call hasher.hash() function (after create the hasher using k as seed)?

Thanks for the quick response. I am new to universal hash function. 
<img width="690" alt="optimal_densification" src="https://github.com/jedisct1/rust-polymur-hash/assets/38149286/44a4ef67-2a1a-47a6-8a64-e097f1e2b239">

The algorithm itself was using something simple to create 2-universal hash function:

<img width="690" alt="Screenshot 2024-01-05 at 7 21 12 PM" src="https://github.com/jedisct1/rust-polymur-hash/assets/38149286/993092f1-b51b-4e95-b37a-98705521d77e">

But I think this lacks a theoretical guarantee.

Thanks,

Jianshu
