### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by carlsverre** [jedisct1/rust-polymur-hash#3]
I may be using this project, so it would be nice to know how you plan on licensing it? The simplest solution would be to follow upstream ([zlib](https://github.com/orlp/polymur-hash/blob/master/LICENSE)) or rust (apache + mit dual).

**Comment by jedisct1** [comment]
License is [MIT](https://github.com/jedisct1/rust-polymur-hash/blob/8cf573bb4f2e73ea7e2cfe2bc9dc3f7a5dc43e9a/Cargo.toml#L8). There's now  a `LICENSE` file in addition to the Cargo property.

Before using it, you should run `cargo bench` to get a benchmark. In my experience, XXHash3 is always faster.

**Comment by carlsverre** [comment]
Thank you! Yea XXHash3 is pretty solid but afaik doesn't have a collision proof which I need for my use case.
